name: Laravel CI  

on:  
  push:  
    branches:  
      - master  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout Code  
      uses: actions/checkout@v2  

    - name: Setup PHP  
      uses: shivammathur/setup-php@v2  
      with:  
        php-version: '8.0' # Sesuaikan versi PHP yang digunakan  
        
    - name: Cache Composer Dependencies  
      uses: actions/cache@v2  
      with:  
        path: vendor  
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}  
        restore-keys: |  
          ${{ runner.os }}-composer-  

    - name: Install Composer Dependencies  
      run: composer install --prefer-dist --no-progress --no-suggest  

    - name: Run Tests  
      run: vendor/bin/phpunit