name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out kode dari repository
      - uses: actions/checkout@v3

      # Setup PHP (sesuaikan versi PHP dan ekstensi sesuai kebutuhan proyek Anda)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath

      # Install dependensi Composer
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Jalankan migrasi database (jika diperlukan)
      #- name: Migrate Database
      #  run: php artisan migrate --force

      # Jalankan testing (pastikan Anda sudah membuat test)
      - name: Run Tests
        run: php artisan test
